config/routes.rb
Rails.application.routes.draw do
  root :to => 'homes#start'
  resources :books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book=Book.new
  end

  def show
    @book=Book.find(params[:id])
  end


  def edit
    @book=Book.find(params[:id])
  end


  def create
    @book=Book.new(book_params)
    if @book.save
      redirect_to book_path(@book.id),notice: 'successfully!!'
    else
      @books = Book.all
      render :index
    end
  end


  def update
    @book=Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book),notice: 'successfully!!'
    else
      render :edit
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to books_path,notice: 'successfully!!'
  end

  private
 # ストロングパラメータ
  def book_params
    params.require(:book).permit(:title,:body)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def start
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/books/edit.html.erb
  <h1>Editing Book</h1>

<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
<% end %>


<%= form_with model:@book do |f| %>

    <div class="field">
      <label>Title</label>
      <%= f.text_field :title %>
    </div>

    <div class="field">
      <label>Body</label>
      <%= f.text_area :body %>
    </div>

    <div class="action">
      <%= f.submit 'Update Book' %>
    </div>
<% end %>


<%= link_to "Show", "/books/#{@book.id}" %>
  |
<a class="back" href="/books">Back</a>

app/views/books/index.html.erb
<p id="notice"><%= flash[:notice] %></p>
<table>
  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.body %></td>

        <td><%= link_to "Show", "/books/#{book.id}" %></td>
        <td><%= link_to "Edit", edit_book_path(book) %></td>
        <td> <%= link_to "Destroy", book_path(book),method: :delete , data: { confirm: 'Are you sure' }%></td>
      </tr>
    <% end %>
  </tbody>
</table>



<% if @book.errors.any? %>
    <h2><%= @book.errors.count %>errors prohibited this book from being saved:</h2>
    <ul>
    <% @book.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
    </ul>
<% end %>


<h1>New book</h1>
<!-- form_with部分 -->
<%= form_with model: @book do |f| %>
  <h4>Title</h4>
  <%= f.text_field :title %>

  <h4>Body</h4>
  <%= f.text_area :body %>

  <%= f.submit  'Create Book' %>
<% end %>

app/views/books/show.html.erb
<p id="notice"><%= flash[:notice] %></p>

<p>
  <strong>Title:</strong>
  <%= @book.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @book.body%>
</p>


<%= link_to "Edit", edit_book_path(@book) %>

<a class="Back" href="/books">Back</a>

app/views/homes/start.html.erb
<h1>ようこそ
  <strong>Bookers</strong>  へ！
</h1>

<p>
  Bookersでは、さまざまな書籍に関するあなたの意見や
</p>

<p>印象を共有し交換することができます</p>

<p><a href="/books">start</a></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>